const GOOGLE_CLIENT_ID = process.env.GOOGLE_CLIENT_ID;
const GOOGLE_CLIENT_SECRET = process.env.GOOGLE_CLIENT_SECRET;
const GITHUB_ID = process.env.GITHUB_ID;
const GITHUB_SECRET = process.env.GITHUB_SECRET;
const BASE_BACKEND_URL = process.env.NEXT_PUBLIC_BASE_BACKEND_URL;
const WEBSOCKET_URL = process.env.NEXT_PUBLIC_WEBSOCKET_URL!;

export {
  GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET,
  GITHUB_ID,
  GITHUB_SECRET,
  BASE_BACKEND_URL,
  WEBSOCKET_URL,
};
